import React from 'react';
import { FileCheck, Printer, HelpCircle, AlertTriangle, UserCheck } from 'lucide-react';
import { LawyerBriefData } from '@/lib/types';

interface LawyerBriefProps {
  briefData: LawyerBriefData;
}

export const LawyerBrief: React.FC<LawyerBriefProps> = ({ briefData }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-8 shadow-sm space-y-6 print:border-none print:shadow-none print:p-0">
      <div className="flex items-center justify-between border-b border-slate-200 pb-4">
        <div>
          <span className="text-[10px] font-bold tracking-widest uppercase text-blue-700 bg-blue-100 px-2.5 py-1 rounded">
            Lawyer-Ready Consultation Brief
          </span>
          <h2 className="text-xl font-bold text-slate-900 mt-1">{briefData.documentTitle}</h2>
          <p className="text-xs text-slate-500">
            Document Type: {briefData.documentType} • Prepared on {briefData.generatedAt}
          </p>
        </div>

        <button
          onClick={handlePrint}
          className="bg-slate-900 text-white text-xs px-4 py-2 rounded-xl font-bold hover:bg-slate-800 transition flex items-center gap-1.5 print:hidden"
        >
          <Printer className="w-4 h-4" /> Print / Save PDF Brief
        </button>
      </div>

      {/* User Context */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 text-xs space-y-1">
        <span className="font-bold text-slate-700 flex items-center gap-1.5">
          <UserCheck className="w-4 h-4 text-slate-500" /> Client Persona & Context:
        </span>
        <p className="text-slate-700">{briefData.userPersona || 'Standard Individual'}</p>
      </div>

      {/* Executive Summary */}
      <div className="text-xs space-y-1">
        <h4 className="font-bold text-slate-900 text-xs uppercase tracking-wider">Executive Overview:</h4>
        <p className="text-slate-700 leading-relaxed bg-slate-50/50 p-3 rounded-xl border border-slate-200">
          {briefData.summary}
        </p>
      </div>

      {/* Flagged Risks */}
      <div className="space-y-2 text-xs">
        <h4 className="font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
          <AlertTriangle className="w-4 h-4 text-red-600" /> Key Flagged Risks for Attorney Review:
        </h4>
        <div className="space-y-2">
          {briefData.topRisks.map((risk, idx) => (
            <div key={idx} className="border border-red-200 bg-red-50/30 rounded-xl p-3">
              <div className="flex items-center justify-between font-bold text-slate-900">
                <span>{risk.clauseTitle}</span>
                <span className="text-[11px] text-red-800 bg-red-100 px-2 py-0.5 rounded">
                  {risk.citation}
                </span>
              </div>
              <p className="text-red-900 text-xs mt-1">{risk.risk}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Questions to Ask Lawyer */}
      <div className="space-y-2 text-xs">
        <h4 className="font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
          <HelpCircle className="w-4 h-4 text-blue-600" /> Specific Questions to Ask Your Lawyer:
        </h4>
        <div className="bg-blue-50/50 border border-blue-200/80 rounded-xl p-4 space-y-2">
          {briefData.questionsForLawyer.map((q, idx) => (
            <div key={idx} className="flex items-start space-x-2 text-blue-950 font-medium">
              <span className="font-bold text-blue-700 shrink-0">{idx + 1}.</span>
              <span>{q}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Legal Footer Notice */}
      <div className="text-[11px] text-slate-400 border-t border-slate-200 pt-4 text-center">
        This brief is generated by Clause2Life for informational preparation only. It does not replace professional legal counsel.
      </div>
    </div>
  );
};
